version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@pg:5432/blog
      QONFIG_NAME: DevConfig
    volumes:
      - ./blog:/app/blog
      ports:
        - 5000:5000
      depends_on:
        - pg

    pg:
        image: postgres:12
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: blog
        volumes:
            - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432


