version: '3.5.2'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@pg:5432/blog
      CONFIG_NAME: ProductionConfig
    volumes:
      - ./blog:/app/blog
    ports:
        - 8080:8080
    depends_on:
        - pg

  pg:
    image: postgres:12
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: blog
    volumes:
        - ${HOME}/projects/gb_flask/pgdata_dev:/var/lib/postgresql
    ports:
        - 5432:5432


