[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Yuliya Bryukhovskikh", email = "makutu@ereb.ru"},
]
dependencies = [
    "Flask>=2.2.3",
    "Flask-SQLAlchemy>=3.0.3",
    "Flask-Login==0.5.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
