"""update user model

Revision ID: 20eb1da3b2f3
Revises: a5fb550f8e98
Create Date: 2023-04-21 21:51:37.218449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eb1da3b2f3'
down_revision = 'a5fb550f8e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
